<?php

use App\Controllers\HomeController;
use App\Controllers\SitemapController;
use App\Controllers\V2\HomeController as V2HomeController;
use App\Controllers\V2\CatalogoController as V2CatalogoController;
use App\Controllers\V2\CategoriasController as V2CategoriasController;
use App\Controllers\V2\CursoController as V2CursoController;
use App\Controllers\V2\LoginController as V2LoginController;
use App\Controllers\V2\CadastroController as V2CadastroController;
use App\Controllers\V2\RecuperarSenhaController as V2RecuperarSenhaController;
use App\Controllers\V2\AlunoController as V2AlunoController;
use App\Controllers\V2\ContaController as V2ContaController;
use App\Controllers\V2\AulaController as V2AulaController;
use App\Controllers\V2\QuizController as V2QuizController;
use App\Controllers\V2\AtividadeController as V2AtividadeController;
use App\Controllers\V2\CertificadoValidacaoController as V2CertificadoValidacaoController;
use App\Controllers\V2\InstitucionalController as V2InstitucionalController;
use App\Controllers\PagesController;
use App\Controllers\AuthController;
use App\Controllers\Admin\RbacController;
use App\Controllers\Admin\UsuariosController as AdminUsuariosController;
use App\Controllers\Admin\PermissoesController as AdminPermissoesController;
use App\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Controllers\Admin\CatalogoController as AdminCatalogoController;
use App\Controllers\Admin\CategoriasController as AdminCategoriasController;
use App\Controllers\Admin\CuponsController;
use App\Controllers\Admin\EmailsController;
use App\Controllers\Admin\EmailModelosController;
use App\Controllers\Admin\FinanceiroController as AdminFinanceiroController;
use App\Controllers\Admin\ConfiguracoesGlobaisController;
use App\Controllers\Admin\CertificadosController as AdminCertificadosController;
use App\Controllers\Admin\CertificadosTemplatesController as AdminCertificadosTemplatesController;
use App\Controllers\Admin\ComprovantesPixController;
use App\Controllers\Admin\ProfessoresFiscaisController as AdminProfessoresFiscaisController;
use App\Controllers\Admin\RateiosController as AdminRateiosController;
use App\Controllers\Admin\PedidosController;
use App\Controllers\Admin\InscricoesController;
use App\Controllers\Admin\AcademicoController as AdminAcademicoController;
use App\Controllers\Admin\CursosController as AdminCursosController;
use App\Controllers\Admin\AvisoController as AdminAvisoController;
use App\Controllers\Admin\PaginasController as AdminPaginasController;
use App\Controllers\Admin\ConfiguracoesPagamentoController;
use App\Controllers\Admin\TurmaEmailsController;
use App\Controllers\Admin\TurmaInscritosController;
use App\Controllers\Admin\TurmasController;
use App\Controllers\Admin\Promocionais\PresentesController;
use App\Controllers\Admin\FrontendModuloController;
use App\Controllers\Admin\FrontendMenuController;
use App\Controllers\Admin\TutorNorminhaController;
use App\Controllers\Professor\CatalogoController as ProfessorCatalogoController;
use App\Controllers\Professor\DashboardController as ProfessorDashboardController;
use App\Controllers\CategoriasController as PublicCategoriasController;
use App\Controllers\CursosController as PublicCursosController;
use App\Controllers\CheckoutController;
use App\Controllers\Webhooks\AbacatePayController;
use App\Controllers\AreaCursoController;
use App\Controllers\QuizController;
use App\Controllers\PedidoRecuperacaoController;
use App\Controllers\MeusCursosController;
use App\Controllers\CertificadosController;
use App\Controllers\Admin\AreaCursoController as AdminAreaCursoController;
use App\Controllers\Admin\QuizController as AdminQuizController;
use App\Controllers\Professor\AreaCursoController as ProfessorAreaCursoController;
use App\Controllers\Professor\AcademicoController as ProfessorAcademicoController;
use App\Controllers\Professor\FinanceiroController as ProfessorFinanceiroController;
use App\Controllers\AvisosController;

// Fase 2.13 — Home da raiz "/" selecionável por configuração (reversível, sem
// alterar código). Padrão: Home V1. Para virar ao V2 após homologação, defina
// HOME_VERSION=v2 no .env (config/app.php → 'home_version'). Nenhuma rota é
// removida; V1 e V2 seguem acessíveis nos seus próprios caminhos.
$app->get('/', function ($request) {
    $homeVersion = (require BASE_PATH . '/config/app.php')['home_version'];
    if ($homeVersion === 'v2') {
        return (new V2HomeController())->index($request);
    }
    return (new HomeController())->index($request);
});
$app->get('/sitemap.xml', array(SitemapController::class, 'index'));
$app->get('/v2', array(V2HomeController::class, 'index'));
$app->get('/v2/catalogo', array(V2CatalogoController::class, 'index'));
$app->get('/v2/categorias', array(V2CategoriasController::class, 'index'));
$app->get('/v2/curso', array(V2CursoController::class, 'index'));
$app->get('/v2/login', array(V2LoginController::class, 'show'));
// Fase 2.13.1 — tela V2 de escolha pós-login (Minha Área × Catálogo). Só é
// alcançada após login direto em /v2/login sem redirect válido. Exige sessão.
$app->get('/v2/pos-login', array(V2LoginController::class, 'posLogin'), array('auth.v2'));
// Logout V2 — encerra a sessão do aluno e retorna sempre a /v2/login (nunca ao
// V1). Somente POST com CSRF (auto) + auth.v2: não há logout inseguro por GET e
// só usuário autenticado alcança a rota. Delega ao AuthService existente.
$app->post('/v2/logout', array(V2LoginController::class, 'logout'), array('auth.v2'));
$app->get('/v2/cadastro', array(V2CadastroController::class, 'show'));
$app->get('/v2/recuperar-senha', array(V2RecuperarSenhaController::class, 'show'));
$app->get('/v2/recuperar-senha/redefinir', array(V2RecuperarSenhaController::class, 'redefinir'));
$app->get('/v2/aluno', array(V2AlunoController::class, 'index'));
$app->post('/v2/aluno/pedidos/cancelar', array(V2AlunoController::class, 'cancelarPedido'));
$app->get('/v2/minha-conta', array(V2ContaController::class, 'editar'));
$app->post('/v2/minha-conta', array(V2ContaController::class, 'atualizar'));
$app->get('/v2/aula', array(V2AulaController::class, 'index'));
$app->post('/v2/aula/concluir', array(V2AulaController::class, 'concluir'));
$app->get('/v2/quiz', array(V2QuizController::class, 'index'));
$app->post('/v2/quiz/iniciar', array(V2QuizController::class, 'iniciar'));
$app->post('/v2/quiz/enviar', array(V2QuizController::class, 'enviar'));
$app->get('/v2/atividade', array(V2AtividadeController::class, 'index'));
$app->post('/v2/atividade/enviar', array(V2AtividadeController::class, 'enviar'));
$app->get('/v2/certificados/validar', array(V2CertificadoValidacaoController::class, 'index'));
$app->post('/v2/certificados/validar', array(V2CertificadoValidacaoController::class, 'index'));
// Fase 2.13B — páginas institucionais EDITÁVEIS no V2. O conteúdo real vem do
// mesmo cadastro do backend (tabela `paginas`, editada em /admin/paginas); a V2
// só consulta e sanitiza. As rotas casam com o slug real de cada página, então
// edições do admin refletem na V2 sem mudança de código.
$app->get('/v2/quem-somos', array(V2InstitucionalController::class, 'quemSomos'));
$app->get('/v2/como-funciona-a-sala-virtual', array(V2InstitucionalController::class, 'comoFuncionaSalaVirtual'));
$app->get('/v2/termos-de-uso', array(V2InstitucionalController::class, 'termosDeUso'));
$app->get('/v2/politica-de-privacidade', array(V2InstitucionalController::class, 'politicaDePrivacidade'));
$app->get('/v2/onde-estamos', array(V2InstitucionalController::class, 'ondeEstamos'));
$app->get('/v2/remova-me', array(V2InstitucionalController::class, 'removaMe'));
// Compatibilidade — rotas demonstrativas antigas redirecionam (301) à canônica
// V2 equivalente (sem loop, sem voltar ao V1).
$app->get('/v2/sobre', array(V2InstitucionalController::class, 'sobre'));
$app->get('/v2/contato', array(V2InstitucionalController::class, 'contato'));
$app->get('/v2/como-funciona', array(V2InstitucionalController::class, 'comoFunciona'));
// Checkout V2 (Fase 2.12A) — casca de apresentação sobre o MESMO CheckoutController.
// O modo V2 é detectado pelo caminho (/v2/checkout...); CSRF automático nos POST.
$app->get('/v2/checkout', array(CheckoutController::class, 'entradaCheckoutV2'));
// Fase 2.13 — etapas V2 protegidas por auth.v2 (visitante → /v2/login?redirect=...,
// nunca /login do V1). O middleware preserva o destino V2 original em GET.
$app->get('/v2/checkout/inscricao', array(CheckoutController::class, 'inscricao'), array('auth.v2'));
$app->post('/v2/checkout/inscricao', array(CheckoutController::class, 'inscricao'), array('auth.v2'));
$app->get('/v2/checkout/participantes', array(CheckoutController::class, 'participantes'), array('auth.v2'));
$app->post('/v2/checkout/participantes', array(CheckoutController::class, 'participantes'), array('auth.v2'));
$app->get('/v2/checkout/resumo', array(CheckoutController::class, 'resumo'), array('auth.v2'));
// Fase 2.12B — Etapa V2 de pagamento (somente GET/leitura). Exige sessão via
// 'auth' (nenhum dado de pedido é exposto a anônimo). O início real do
// AbacatePay é feito por POST HTML nativo ao endpoint legado já existente
// (/aluno/pedidos/pagar/abacatepay); não há POST V2 dedicado.
$app->get('/v2/checkout/pagamento', array(CheckoutController::class, 'pagamento'), array('auth.v2'));
// Fase 2.12C — Comprovante PIX em visual V2. GET apenas apresenta o que o backend
// já autoriza (mesma checagem de propriedade de detalharCheckout); exige sessão
// via 'auth', portanto nenhum dado de pedido é exposto a anônimo. O POST de envio
// tem rota V2 dedicada e fina (enviarComprovanteV2) que delega INTEGRALMENTE o
// arquivo/payload ao mesmo ComprovantePixService do fluxo legado e faz PRG para
// uma URL interna fixa V2. CSRF automático no POST (rota normal, não postWithoutCsrf).
// O caminho de envio é /v2/checkout/comprovante/enviar: NÃO há diretório físico
// 'comprovante' (evita o DirectorySlash do Apache que converteria POST em GET).
$app->get('/v2/checkout/comprovante', array(CheckoutController::class, 'comprovante'), array('auth.v2'));
$app->post('/v2/checkout/comprovante/enviar', array(CheckoutController::class, 'enviarComprovanteV2'), array('auth.v2'));
// Confirmação V2 pós-envio (somente leitura). Mantém o aluno no namespace /v2/;
// revalida a propriedade do pedido em detalharCheckout.
$app->get('/v2/checkout/comprovante/enviado', array(CheckoutController::class, 'comprovanteEnviadoV2'), array('auth.v2'));
$app->get('/categorias', array(PublicCategoriasController::class, 'index'));
$app->get('/categorias/{slug}/cursos', array(PublicCategoriasController::class, 'cursos'));
$app->get('/cursos', array(PublicCursosController::class, 'index'));
$app->get('/cursos/detalhe', array(PublicCursosController::class, 'show'));
$app->get('/cupom', array(CheckoutController::class, 'cupomPromocional'));
$app->get('/como-funciona', array(PagesController::class, 'comoFunciona'));
$app->get('/sobre', array(PagesController::class, 'sobre'));
$app->get('/contato', array(PagesController::class, 'contato'));
$app->get('/inscricao', array(CheckoutController::class, 'inscricao'));
$app->post('/inscricao', array(CheckoutController::class, 'inscricao'));
$app->get('/checkout/inscricao', array(CheckoutController::class, 'inscricao'));
$app->post('/checkout/inscricao', array(CheckoutController::class, 'inscricao'));
$app->get('/checkout/participantes', array(CheckoutController::class, 'participantes'));
$app->post('/checkout/participantes', array(CheckoutController::class, 'participantes'));
$app->get('/checkout/resumo', array(CheckoutController::class, 'resumo'));
$app->get('/checkout/cupom', array(CheckoutController::class, 'cupom'));
$app->post('/checkout/cupom', array(CheckoutController::class, 'cupom'));
$app->get('/checkout/comprovante', array(CheckoutController::class, 'comprovante'));
$app->post('/checkout/comprovante', array(CheckoutController::class, 'comprovante'));
$app->get('/checkout/sucesso', array(CheckoutController::class, 'sucesso'), array('auth'));
$app->post('/aluno/pedidos/pagar/abacatepay', array(CheckoutController::class, 'pagarAbacatepay'), array('auth'));
$app->postWithoutCsrf('/webhooks/abacatepay', array(AbacatePayController::class, 'handle'));
$app->get('/meus-cursos', array(MeusCursosController::class, 'index'), array('auth'));
$app->get('/aluno/meus-cursos', array(MeusCursosController::class, 'index'), array('auth'));
$app->get('/pedidos', array(MeusCursosController::class, 'index'), array('auth'));
$app->post('/meus-cursos/pedidos/cancelar', array(MeusCursosController::class, 'cancelarPedido'), array('auth'));
$app->post('/aluno/meus-cursos/pedidos/cancelar', array(MeusCursosController::class, 'cancelarPedido'), array('auth'));
$app->get('/minha-pagina', array(AuthController::class, 'minhaPagina'), array('auth'));
$app->get('/minha-conta', array(AuthController::class, 'showAccount'), array('auth'));
$app->post('/minha-conta', array(AuthController::class, 'updateAccount'), array('auth'));
$app->get('/area-curso', array(AreaCursoController::class, 'index'), array('auth'));
$app->get('/aluno/cursos', array(AreaCursoController::class, 'index'), array('auth'));
$app->get('/aluno/curso/{inscricao_id}/{curso_id}/{turma_id}', array(AreaCursoController::class, 'index'), array('auth'));
$app->get('/area-curso/modulo', array(AreaCursoController::class, 'modulo'), array('auth'));
$app->get('/aluno/cursos/modulo', array(AreaCursoController::class, 'modulo'), array('auth'));
$app->get('/aluno/curso/{inscricao_id}/{curso_id}/{turma_id}/modulo/{modulo_id}', array(AreaCursoController::class, 'modulo'), array('auth'));
$app->post('/area-curso/modulo/concluir-aula', array(AreaCursoController::class, 'concluirAula'), array('auth'));
$app->post('/aluno/cursos/modulo/concluir-aula', array(AreaCursoController::class, 'concluirAula'), array('auth'));
$app->post('/area-curso/modulo/concluir-modulo', array(AreaCursoController::class, 'concluirModulo'), array('auth'));
$app->post('/aluno/cursos/modulo/concluir-modulo', array(AreaCursoController::class, 'concluirModulo'), array('auth'));
$app->get('/area-curso/material', array(AreaCursoController::class, 'material'), array('auth'));
$app->get('/aluno/cursos/material', array(AreaCursoController::class, 'material'), array('auth'));
$app->get('/area-curso/conteudo/item', array(AreaCursoController::class, 'conteudoItem'), array('auth'));
$app->get('/aluno/cursos/conteudo/item', array(AreaCursoController::class, 'conteudoItem'), array('auth'));
$app->get('/aluno/curso/{inscricao_id}/{curso_id}/{turma_id}/modulo/{modulo_id}/conteudo/{conteudo_id}', array(AreaCursoController::class, 'conteudoItem'), array('auth'));
$app->post('/area-curso/conteudo/item/concluir', array(AreaCursoController::class, 'concluirConteudoItem'), array('auth'));
$app->post('/aluno/cursos/conteudo/item/concluir', array(AreaCursoController::class, 'concluirConteudoItem'), array('auth'));
$app->post('/area-curso/conteudo/avaliacao/enviar', array(AreaCursoController::class, 'enviarConteudoAvaliacao'), array('auth'));
$app->post('/aluno/cursos/conteudo/avaliacao/enviar', array(AreaCursoController::class, 'enviarConteudoAvaliacao'), array('auth'));
$app->get('/aluno/cursos/conteudo/avaliacao/imagem', array(AreaCursoController::class, 'entregaAvaliacaoImagem'), array('auth'));
$app->get('/area-curso/conteudo/arquivo/download', array(AreaCursoController::class, 'downloadConteudoArquivo'), array('auth'));
$app->get('/aluno/cursos/conteudo/arquivo/download', array(AreaCursoController::class, 'downloadConteudoArquivo'), array('auth'));
$app->get('/area-curso/conteudo/link/acessar', array(AreaCursoController::class, 'acessarConteudoLink'), array('auth'));
$app->get('/aluno/cursos/conteudo/link/acessar', array(AreaCursoController::class, 'acessarConteudoLink'), array('auth'));
$app->post('/aluno/cursos/atividade/enviar', array(AreaCursoController::class, 'enviarAtividade'), array('auth'));
$app->get('/aluno/cursos/atividade/arquivo', array(AreaCursoController::class, 'entregaArquivo'), array('auth'));
$app->post('/aluno/cursos/quiz/iniciar', array(QuizController::class, 'iniciar'), array('auth'));
$app->post('/aluno/cursos/quiz/rascunho', array(QuizController::class, 'salvarRascunho'), array('auth'));
$app->post('/aluno/cursos/quiz/enviar', array(QuizController::class, 'enviar'), array('auth'));
$app->post('/aluno/cursos/quiz/revisao', array(QuizController::class, 'marcarRevisao'), array('auth'));
$app->post('/aluno/cursos/quiz/tempo', array(QuizController::class, 'tempo'), array('auth'));
$app->get('/aluno/cursos/quiz/resultado', array(QuizController::class, 'resultado'), array('auth'));
$app->post('/avisos/ocultar', array(AvisosController::class, 'ocultar'), array('auth'));
$app->get('/cadastro', array(AuthController::class, 'showRegister'));
$app->post('/cadastro', array(AuthController::class, 'register'));
$app->get('/login', array(AuthController::class, 'showLogin'));
$app->post('/login', array(AuthController::class, 'login'));
$app->get('/logout', array(AuthController::class, 'logoutConfirm'), array('auth'));
$app->post('/logout', array(AuthController::class, 'logout'), array('auth'));
$app->get('/recuperar-senha', array(AuthController::class, 'showForgotPassword'));
$app->post('/recuperar-senha', array(AuthController::class, 'requestPasswordReset'));
$app->get('/recuperar-senha/redefinir', array(AuthController::class, 'showResetPassword'));
$app->post('/recuperar-senha/redefinir', array(AuthController::class, 'resetPassword'));
$app->get('/esqueci-minha-senha', array(AuthController::class, 'showForgotPassword'));
$app->post('/esqueci-minha-senha', array(AuthController::class, 'requestPasswordReset'));
$app->get('/esqueci-minha-senha/redefinir', array(AuthController::class, 'showResetPassword'));
$app->post('/esqueci-minha-senha/redefinir', array(AuthController::class, 'resetPassword'));
$app->get('/admin/rbac', array(RbacController::class, 'index'), array('auth', 'permission:rbac.dashboard.ver'));
$app->get('/admin', array(AdminDashboardController::class, 'index'), array('auth'));
$app->get('/admin/dashboard', array(AdminDashboardController::class, 'index'), array('auth'));
$app->post('/admin/dashboard/superadmins-turmas/sincronizar', array(AdminDashboardController::class, 'sincronizarSuperadminsTurmas'), array('auth', 'permission:rbac.dashboard.ver'));
$app->get('/admin/catalogo', array(AdminCatalogoController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/categorias', array(AdminCategoriasController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/categorias/criar', array(AdminCategoriasController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/categorias/criar', array(AdminCategoriasController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/categorias/editar', array(AdminCategoriasController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/categorias/editar', array(AdminCategoriasController::class, 'update'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/categorias/show', array(AdminCategoriasController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/categorias/excluir', array(AdminCategoriasController::class, 'destroy'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/rbac/perfis/permissoes', array(RbacController::class, 'syncProfilePermissions'), array('auth', 'permission:rbac.perfis.gerenciar'));
$app->post('/admin/rbac/usuarios/perfis', array(RbacController::class, 'syncUserProfiles'), array('auth', 'permission:rbac.perfis.gerenciar'));
$app->get('/admin/usuarios', array(AdminUsuariosController::class, 'index'), array('auth', 'permission:usuarios.ver'));
$app->get('/admin/usuarios/criar', array(AdminUsuariosController::class, 'create'), array('auth', 'permission:usuarios.gerenciar'));
$app->post('/admin/usuarios/criar', array(AdminUsuariosController::class, 'store'), array('auth', 'permission:usuarios.gerenciar'));
$app->get('/admin/usuarios/editar', array(AdminUsuariosController::class, 'edit'), array('auth', 'permission:usuarios.gerenciar'));
$app->post('/admin/usuarios/editar', array(AdminUsuariosController::class, 'update'), array('auth', 'permission:usuarios.gerenciar'));
$app->post('/admin/usuarios/excluir', array(AdminUsuariosController::class, 'destroy'), array('auth', 'permission:usuarios.gerenciar'));
$app->get('/admin/permissoes', array(AdminPermissoesController::class, 'index'), array('auth', 'permission:rbac.permissoes.ver'));
$app->get('/admin/permissoes/perfil/criar', array(AdminPermissoesController::class, 'perfilForm'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->post('/admin/permissoes/perfil/criar', array(AdminPermissoesController::class, 'perfilStore'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->get('/admin/permissoes/perfil/editar', array(AdminPermissoesController::class, 'perfilForm'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->post('/admin/permissoes/perfil/editar', array(AdminPermissoesController::class, 'perfilUpdate'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->post('/admin/permissoes/perfil/excluir', array(AdminPermissoesController::class, 'perfilDestroy'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->get('/admin/permissoes/item/criar', array(AdminPermissoesController::class, 'permissaoForm'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->post('/admin/permissoes/item/criar', array(AdminPermissoesController::class, 'permissaoStore'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->get('/admin/permissoes/item/editar', array(AdminPermissoesController::class, 'permissaoForm'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->post('/admin/permissoes/item/editar', array(AdminPermissoesController::class, 'permissaoUpdate'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->post('/admin/permissoes/item/excluir', array(AdminPermissoesController::class, 'permissaoDestroy'), array('auth', 'permission:rbac.permissoes.gerenciar'));
$app->get('/admin/cursos', array(AdminCursosController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/cursos/criar', array(AdminCursosController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/cursos/criar', array(AdminCursosController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/cursos/editar', array(AdminCursosController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/cursos/editar', array(AdminCursosController::class, 'update'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/cursos/show', array(AdminCursosController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/cursos/excluir', array(AdminCursosController::class, 'destroy'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/cursos/status', array(AdminCursosController::class, 'updateStatus'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/avisos', array(AdminAvisoController::class, 'index'), array('auth', 'permission:avisos.visualizar'));
$app->get('/admin/avisos/criar', array(AdminAvisoController::class, 'create'), array('auth', 'permission:avisos.criar'));
$app->post('/admin/avisos/criar', array(AdminAvisoController::class, 'store'), array('auth', 'permission:avisos.criar'));
$app->get('/admin/avisos/editar', array(AdminAvisoController::class, 'edit'), array('auth', 'permission:avisos.editar'));
$app->post('/admin/avisos/editar', array(AdminAvisoController::class, 'update'), array('auth', 'permission:avisos.editar'));
$app->get('/admin/avisos/show', array(AdminAvisoController::class, 'show'), array('auth', 'permission:avisos.visualizar'));
$app->get('/admin/avisos/alunos', array(AdminAvisoController::class, 'alunos'), array('auth', 'permission:avisos.visualizar'));
$app->get('/admin/avisos/destinatarios', array(AdminAvisoController::class, 'destinatarios'), array('auth', 'permission:avisos.visualizar'));
$app->post('/admin/avisos/enviar', array(AdminAvisoController::class, 'enviar'), array('auth', 'permission:avisos.enviar'));
$app->post('/admin/avisos/excluir', array(AdminAvisoController::class, 'destroy'), array('auth', 'permission:avisos.excluir'));
$app->get('/admin/paginas', array(AdminPaginasController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/paginas/criar', array(AdminPaginasController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/paginas/criar', array(AdminPaginasController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/paginas/editar', array(AdminPaginasController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/paginas/editar', array(AdminPaginasController::class, 'update'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/paginas/show', array(AdminPaginasController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/paginas/excluir', array(AdminPaginasController::class, 'destroy'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas', array(TurmasController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/turmas/criar', array(TurmasController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/criar', array(TurmasController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas/editar', array(TurmasController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/editar', array(TurmasController::class, 'update'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas/show', array(TurmasController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/turmas/excluir', array(TurmasController::class, 'destroy'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/status', array(TurmasController::class, 'updateStatus'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas/inscritos', array(TurmaInscritosController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/turmas/inscritos/exportar', array(TurmaInscritosController::class, 'exportarCsv'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/turmas/inscritos/exportar-pdf', array(TurmaInscritosController::class, 'exportarPdf'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/turmas/emails', array(TurmaEmailsController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/turmas/emails/novo', array(TurmaEmailsController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/emails/enviar', array(TurmaEmailsController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/emails/processar', array(TurmaEmailsController::class, 'processar'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas/emails/detalhe', array(TurmaEmailsController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/professores-fiscais', array(AdminProfessoresFiscaisController::class, 'index'), array('auth', 'permission:financeiro.ver'));
$app->get('/admin/professores-fiscais/criar', array(AdminProfessoresFiscaisController::class, 'create'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/professores-fiscais/criar', array(AdminProfessoresFiscaisController::class, 'store'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/professores-fiscais/editar', array(AdminProfessoresFiscaisController::class, 'edit'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/professores-fiscais/editar', array(AdminProfessoresFiscaisController::class, 'update'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/professores-fiscais/show', array(AdminProfessoresFiscaisController::class, 'show'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/professores-fiscais/excluir', array(AdminProfessoresFiscaisController::class, 'destroy'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/rateios', array(AdminRateiosController::class, 'index'), array('auth', 'permission:financeiro.ver'));
$app->get('/admin/rateios/criar', array(AdminRateiosController::class, 'create'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/rateios/criar', array(AdminRateiosController::class, 'store'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/rateios/editar', array(AdminRateiosController::class, 'edit'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/rateios/editar', array(AdminRateiosController::class, 'update'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/rateios/show', array(AdminRateiosController::class, 'show'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/rateios/excluir', array(AdminRateiosController::class, 'destroy'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/promocionais/presentes', array(PresentesController::class, 'index'), array('auth', 'permission:promocionais.presentes.ver'));
$app->get('/admin/promocionais/presentes/criar', array(PresentesController::class, 'create'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->get('/admin/promocionais/presentes/configurar', array(PresentesController::class, 'configurar'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->post('/admin/promocionais/presentes/selecionar', array(PresentesController::class, 'selecionar'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->post('/admin/promocionais/presentes/selecionar-limpar', array(PresentesController::class, 'limparSelecao'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->post('/admin/promocionais/presentes/selecionado-remover', array(PresentesController::class, 'removerSelecionado'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->post('/admin/promocionais/presentes/preview', array(PresentesController::class, 'preview'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->post('/admin/promocionais/presentes/store', array(PresentesController::class, 'store'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->get('/admin/promocionais/presentes/show', array(PresentesController::class, 'show'), array('auth', 'permission:promocionais.presentes.ver'));
$app->post('/admin/promocionais/presentes/cancelar', array(PresentesController::class, 'cancelar'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->post('/admin/promocionais/presentes/cancelar-lote', array(PresentesController::class, 'cancelarLote'), array('auth', 'permission:promocionais.presentes.gerenciar'));
$app->get('/admin/pedidos', array(PedidosController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/pedidos/criar', array(PedidosController::class, 'criar'), array('auth', 'permission:pedidos.gerenciar'));
$app->post('/admin/pedidos/criar', array(PedidosController::class, 'criar'), array('auth', 'permission:pedidos.gerenciar'));
$app->get('/admin/pedidos/alunos', array(PedidosController::class, 'alunos'), array('auth', 'permission:pedidos.gerenciar'));
$app->get('/admin/pedidos/excluidos', array(PedidosController::class, 'excluidos'), array('auth', 'permission:pedidos.gerenciar'));
$app->get('/admin/pedidos/show', array(PedidosController::class, 'show'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/excluir', array(PedidosController::class, 'excluir'), array('auth', 'permission:pedidos.gerenciar'));
$app->post('/admin/pedidos/reverter-cancelamento', array(PedidosController::class, 'reverterCancelamento'), array('auth', 'permission:pedidos.gerenciar'));
$app->post('/admin/pedidos/reabrir-aguardando-pagamento', array(PedidosController::class, 'reabrirComoAguardandoPagamento'), array('auth', 'permission:pedidos.gerenciar'));
$app->post('/admin/pedidos/rascunho-aguardando-pagamento', array(PedidosController::class, 'marcarRascunhoComoAguardandoPagamento'), array('auth', 'permission:pedidos.gerenciar'));
$app->post('/admin/pedidos/excluir-lote', array(PedidosController::class, 'excluirEmLote'), array('auth', 'permission:pedidos.gerenciar'));
$app->post('/admin/pedidos/cupom-manual', array(PedidosController::class, 'cupomManual'), array('auth', 'permission:pedidos.gerenciar'));
$app->get('/admin/pedidos/recuperacao', array(PedidosController::class, 'recuperacao'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/recuperacao/enviar', array(PedidosController::class, 'enviarRecuperacao'), array('auth', 'permission:pedidos.gerenciar'));
$app->post('/admin/pedidos/recuperacao/enviar-lote', array(PedidosController::class, 'enviarRecuperacaoLote'), array('auth', 'permission:pedidos.gerenciar'));
$app->get('/admin/pedidos/comprovante', array(PedidosController::class, 'comprovante'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/comprovante', array(PedidosController::class, 'anexarComprovante'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/aprovar', array(PedidosController::class, 'aprovar'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/marcar-pendencia', array(PedidosController::class, 'marcarPendencia'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/solicitar-reenvio', array(PedidosController::class, 'solicitarReenvio'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/inscricoes', array(InscricoesController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/inscricoes/status', array(InscricoesController::class, 'alterarStatus'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/comprovantes-pix', array(ComprovantesPixController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/comprovantes-pix/aprovar', array(ComprovantesPixController::class, 'aprovar'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/comprovantes-pix/reprovar', array(ComprovantesPixController::class, 'reprovar'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/academico', array(AdminAcademicoController::class, 'index'), array('auth', 'permission:academico.ver'));
$app->post('/admin/academico/configuracao', array(AdminAcademicoController::class, 'salvarConfiguracao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/presenca', array(AdminAcademicoController::class, 'registrarPresenca'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/avaliacao', array(AdminAcademicoController::class, 'salvarAvaliacao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/pergunta', array(AdminAcademicoController::class, 'salvarPergunta'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/nota', array(AdminAcademicoController::class, 'registrarNota'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/recalcular', array(AdminAcademicoController::class, 'recalcularAptidao'), array('auth', 'permission:academico.gerenciar'));
$app->get('/admin/cupons', array(CuponsController::class, 'index'), array('auth', 'permission:cupons.ver'));
$app->get('/admin/cupons/criar', array(CuponsController::class, 'create'), array('auth', 'permission:cupons.gerenciar'));
$app->post('/admin/cupons/criar', array(CuponsController::class, 'store'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/cupons/editar', array(CuponsController::class, 'edit'), array('auth', 'permission:cupons.gerenciar'));
$app->post('/admin/cupons/editar', array(CuponsController::class, 'update'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/cupons/resumo', array(CuponsController::class, 'show'), array('auth', 'permission:cupons.usos.ver'));
$app->post('/admin/cupons/status', array(CuponsController::class, 'status'), array('auth', 'permission:cupons.gerenciar'));
$app->post('/admin/cupons/excluir', array(CuponsController::class, 'destroy'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/emails', array(EmailsController::class, 'index'), array('auth', 'permission:emails.ver'));
$app->post('/admin/emails', array(EmailsController::class, 'save'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/teste', array(EmailsController::class, 'teste'), array('auth', 'permission:emails.gerenciar'));
$app->get('/admin/emails/fila', array(EmailsController::class, 'fila'), array('auth', 'permission:emails.ver'));
$app->post('/admin/emails/reenviar', array(EmailsController::class, 'reenviar'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/reenviar-selecionados', array(EmailsController::class, 'reenviarSelecionados'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/reenviar-pendentes', array(EmailsController::class, 'reenviarPendentes'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/excluir-falha', array(EmailsController::class, 'excluirFalha'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/excluir-falhas-selecionadas', array(EmailsController::class, 'excluirFalhasSelecionadas'), array('auth', 'permission:emails.gerenciar'));
$app->get('/admin/emails/modelos', array(EmailModelosController::class, 'index'), array('auth', 'permission:emails.ver'));
$app->get('/admin/emails/modelos/criar', array(EmailModelosController::class, 'create'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/modelos/criar', array(EmailModelosController::class, 'store'), array('auth', 'permission:emails.gerenciar'));
$app->get('/admin/emails/modelos/editar', array(EmailModelosController::class, 'edit'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/modelos/editar', array(EmailModelosController::class, 'update'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/modelos/status', array(EmailModelosController::class, 'toggleStatus'), array('auth', 'permission:emails.gerenciar'));
$app->post('/admin/emails/modelos/restaurar-padrao', array(EmailModelosController::class, 'restoreDefault'), array('auth', 'permission:emails.gerenciar'));
$app->get('/pedido-recuperacao/descadastrar', array(PedidoRecuperacaoController::class, 'descadastrar'));
$app->get('/admin/financeiro', array(AdminFinanceiroController::class, 'index'), array('auth', 'permission:financeiro.ver'));
$app->get('/admin/financeiro/entradas/exportar', array(AdminFinanceiroController::class, 'exportarEntradas'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/financeiro/apurar', array(AdminFinanceiroController::class, 'apurar'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/financeiro/repasses', array(AdminFinanceiroController::class, 'repasses'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/financeiro/repasses/gerar', array(AdminFinanceiroController::class, 'gerarRepasses'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/financeiro/professor-fiscal', array(AdminFinanceiroController::class, 'salvarProfessorFiscal'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/financeiro/documento', array(AdminFinanceiroController::class, 'registrarDocumento'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/financeiro/pagamento', array(AdminFinanceiroController::class, 'registrarPagamento'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/configuracoes-globais', array(ConfiguracoesGlobaisController::class, 'index'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais', array(ConfiguracoesGlobaisController::class, 'salvarInstitucional'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-pagamento', array(ConfiguracoesPagamentoController::class, 'index'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->post('/admin/configuracoes-pagamento/salvar', array(ConfiguracoesPagamentoController::class, 'salvar'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->post('/admin/configuracoes-pagamento/testar-abacatepay', array(ConfiguracoesPagamentoController::class, 'testarAbacatePay'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->post('/admin/configuracoes-pagamento/gerar-webhook-secret', array(ConfiguracoesPagamentoController::class, 'gerarWebhookSecret'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/certificados', array(ConfiguracoesGlobaisController::class, 'certificados'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/certificados', array(ConfiguracoesGlobaisController::class, 'salvarCertificados'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/financeiro', array(ConfiguracoesGlobaisController::class, 'financeiro'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/financeiro', array(ConfiguracoesGlobaisController::class, 'salvarFinanceiro'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/frontend', array(ConfiguracoesGlobaisController::class, 'frontend'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/frontend', array(ConfiguracoesGlobaisController::class, 'salvarFrontend'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/seguranca', array(ConfiguracoesGlobaisController::class, 'seguranca'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/seguranca', array(ConfiguracoesGlobaisController::class, 'salvarSeguranca'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/area-curso', array(AdminAreaCursoController::class, 'index'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/instrucoes', array(AdminAreaCursoController::class, 'salvarInstrucao'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/modulos', array(AdminAreaCursoController::class, 'salvarModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/aulas', array(AdminAreaCursoController::class, 'salvarAula'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/materiais', array(AdminAreaCursoController::class, 'salvarMaterial'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/atividades', array(AdminAreaCursoController::class, 'salvarAtividade'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/atividades/status', array(AdminAreaCursoController::class, 'alterarStatusAtividade'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/atividades/entregas/corrigir', array(AdminAreaCursoController::class, 'corrigirEntrega'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/atividades/entregas/devolver', array(AdminAreaCursoController::class, 'devolverEntrega'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/atividades/entregas/arquivo', array(AdminAreaCursoController::class, 'entregaArquivo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/criterios-conclusao', array(AdminAreaCursoController::class, 'salvarCriteriosConclusao'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/links', array(AdminAreaCursoController::class, 'salvarLink'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/excluir', array(AdminAreaCursoController::class, 'excluir'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/modulo/salvar', array(AdminAreaCursoController::class, 'salvarConteudoModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/modulo/arquivar', array(AdminAreaCursoController::class, 'arquivarConteudoModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/modulo/duplicar', array(AdminAreaCursoController::class, 'duplicarConteudoModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/modulo/excluir-definitivamente', array(AdminAreaCursoController::class, 'excluirDefinitivamenteConteudoModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/modulos/ordenar', array(AdminAreaCursoController::class, 'ordenarConteudoModulos'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/modulos/criar', array(AdminAreaCursoController::class, 'criarConteudoModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/modulos/editar', array(AdminAreaCursoController::class, 'editarConteudoModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/item/salvar', array(AdminAreaCursoController::class, 'salvarConteudoItem'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/item/arquivar', array(AdminAreaCursoController::class, 'arquivarConteudoItem'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/item/duplicar', array(AdminAreaCursoController::class, 'duplicarConteudoItem'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/item/excluir-definitivamente', array(AdminAreaCursoController::class, 'excluirDefinitivamenteConteudoItem'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/item/mover', array(AdminAreaCursoController::class, 'moverConteudoItem'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/itens/ordenar', array(AdminAreaCursoController::class, 'ordenarConteudoItens'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/itens/criar', array(AdminAreaCursoController::class, 'criarConteudoItem'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/itens/editar', array(AdminAreaCursoController::class, 'editarConteudoItem'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/arquivo/download', array(AdminAreaCursoController::class, 'downloadConteudoArquivo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/html/preview', array(AdminAreaCursoController::class, 'previewConteudoHtml'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/avaliacoes/pendentes', array(AdminAreaCursoController::class, 'avaliacoesTextuaisPendentes'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/avaliacao/corrigir', array(AdminAreaCursoController::class, 'avaliacaoTextualCorrigir'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/avaliacao/corrigir', array(AdminAreaCursoController::class, 'corrigirAvaliacaoTextual'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/avaliacao/liberar-reenvio', array(AdminAreaCursoController::class, 'liberarReenvioAvaliacaoTextual'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/avaliacao/imagem', array(AdminAreaCursoController::class, 'entregaAvaliacaoImagem'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/avaliacoes/exportar', array(AdminAreaCursoController::class, 'exportarAvaliacoesConteudoCsv'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/quiz/perguntas', array(AdminQuizController::class, 'editarPerguntas'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/pergunta/salvar', array(AdminQuizController::class, 'salvarPergunta'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/pergunta/excluir', array(AdminQuizController::class, 'excluirPergunta'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/perguntas/reordenar', array(AdminQuizController::class, 'reordenarPerguntas'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/quiz/blocos', array(AdminQuizController::class, 'blocos'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/bloco/salvar', array(AdminQuizController::class, 'salvarBloco'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/bloco/excluir', array(AdminQuizController::class, 'excluirBloco'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/bloco/status', array(AdminQuizController::class, 'alternarStatusBloco'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/blocos/reordenar', array(AdminQuizController::class, 'reordenarBlocos'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/quiz/discursivas', array(AdminQuizController::class, 'discursivas'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/discursiva/corrigir', array(AdminQuizController::class, 'corrigirDiscursiva'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/quiz/resultados', array(AdminQuizController::class, 'resultados'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/conteudo/quiz/reset-aluno', array(AdminQuizController::class, 'resetarAluno'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/conteudo/quiz/preview', array(AdminQuizController::class, 'preview'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/participantes', array(AdminAreaCursoController::class, 'participantes'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/material', array(AdminAreaCursoController::class, 'material'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/frontend/modulos', array(FrontendModuloController::class, 'index'), array('auth', 'permission:frontend.modulos.ver'));
$app->get('/admin/frontend/modulos/criar', array(FrontendModuloController::class, 'create'), array('auth', 'permission:frontend.modulos.gerenciar'));
$app->post('/admin/frontend/modulos/criar', array(FrontendModuloController::class, 'store'), array('auth', 'permission:frontend.modulos.gerenciar'));
$app->get('/admin/frontend/modulos/editar', array(FrontendModuloController::class, 'edit'), array('auth', 'permission:frontend.modulos.gerenciar'));
$app->post('/admin/frontend/modulos/editar', array(FrontendModuloController::class, 'update'), array('auth', 'permission:frontend.modulos.gerenciar'));
$app->post('/admin/frontend/modulos/excluir', array(FrontendModuloController::class, 'destroy'), array('auth', 'permission:frontend.modulos.gerenciar'));
$app->get('/admin/frontend/menus', array(FrontendMenuController::class, 'index'), array('auth', 'permission:frontend.menus.ver'));
$app->get('/admin/frontend/menus/criar', array(FrontendMenuController::class, 'create'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->post('/admin/frontend/menus/criar', array(FrontendMenuController::class, 'store'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->get('/admin/frontend/menus/editar', array(FrontendMenuController::class, 'edit'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->post('/admin/frontend/menus/editar', array(FrontendMenuController::class, 'update'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->post('/admin/frontend/menus/excluir', array(FrontendMenuController::class, 'destroy'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->get('/admin/frontend/menus/itens', array(FrontendMenuController::class, 'itens'), array('auth', 'permission:frontend.menus.ver'));
$app->get('/admin/frontend/menus/itens/criar', array(FrontendMenuController::class, 'itemCreate'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->post('/admin/frontend/menus/itens/criar', array(FrontendMenuController::class, 'itemStore'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->get('/admin/frontend/menus/itens/editar', array(FrontendMenuController::class, 'itemEdit'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->post('/admin/frontend/menus/itens/editar', array(FrontendMenuController::class, 'itemUpdate'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->post('/admin/frontend/menus/itens/excluir', array(FrontendMenuController::class, 'itemDestroy'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->post('/admin/frontend/menus/itens/reordenar', array(FrontendMenuController::class, 'itensReordenar'), array('auth', 'permission:frontend.menus.gerenciar'));
$app->get('/admin/tutor-norminha', array(TutorNorminhaController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/tutor-norminha/criar', array(TutorNorminhaController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/tutor-norminha/editar', array(TutorNorminhaController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/tutor-norminha/salvar', array(TutorNorminhaController::class, 'salvar'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/tutor-norminha/status', array(TutorNorminhaController::class, 'status'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/tutor-norminha/configuracoes', array(TutorNorminhaController::class, 'configuracoes'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/tutor-norminha/configuracoes/salvar', array(TutorNorminhaController::class, 'salvarConfiguracoes'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/certificados', array(AdminCertificadosController::class, 'index'), array('auth', 'permission:certificados.ver'));
$app->get('/admin/certificados/show', array(AdminCertificadosController::class, 'show'), array('auth', 'permission:certificados.ver'));
$app->get('/admin/certificados/emitir', array(AdminCertificadosController::class, 'emitir'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/emitir', array(AdminCertificadosController::class, 'emitir'), array('auth', 'permission:certificados.gerenciar'));
$app->get('/admin/certificados/emissao-manual', array(AdminCertificadosController::class, 'emissaoManual'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/emissao-manual/emitir', array(AdminCertificadosController::class, 'emissaoManualEmitir'), array('auth', 'permission:certificados.gerenciar'));
$app->get('/admin/certificados/emissao-rapida-individual', array(AdminCertificadosController::class, 'emissaoRapidaIndividual'), array('auth', 'permission:certificados.ver'));
$app->post('/admin/certificados/emissao-rapida-individual/emitir', array(AdminCertificadosController::class, 'emissaoRapidaIndividualEmitir'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/reemitir', array(AdminCertificadosController::class, 'reemitir'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/cancelar', array(AdminCertificadosController::class, 'cancelar'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/revogar', array(AdminCertificadosController::class, 'revogar'), array('auth', 'permission:certificados.gerenciar'));
$app->get('/admin/certificados/pdf', array(AdminCertificadosController::class, 'pdf'), array('auth', 'permission:certificados.ver'));
$app->get('/admin/certificados/templates', array(AdminCertificadosTemplatesController::class, 'index'), array('auth', 'permission:certificados.ver'));
$app->get('/admin/certificados/templates/criar', array(AdminCertificadosTemplatesController::class, 'create'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/templates/criar', array(AdminCertificadosTemplatesController::class, 'store'), array('auth', 'permission:certificados.gerenciar'));
$app->get('/admin/certificados/templates/editar', array(AdminCertificadosTemplatesController::class, 'edit'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/templates/editar', array(AdminCertificadosTemplatesController::class, 'update'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/templates/excluir', array(AdminCertificadosTemplatesController::class, 'excluir'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/templates/duplicar', array(AdminCertificadosTemplatesController::class, 'duplicar'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/templates/definir-padrao', array(AdminCertificadosTemplatesController::class, 'definirPadrao'), array('auth', 'permission:certificados.gerenciar'));
$app->get('/admin/certificados/templates/preview', array(AdminCertificadosTemplatesController::class, 'preview'), array('auth', 'permission:certificados.ver'));
$app->get('/certificados/validar', array(CertificadosController::class, 'validar'));
$app->get('/certificados', array(CertificadosController::class, 'validar'));
$app->post('/certificados/validar', array(CertificadosController::class, 'validar'));
$app->get('/certificados/show', array(CertificadosController::class, 'show'));
$app->get('/certificados/versao-online', array(CertificadosController::class, 'versaoOnline'));
$app->get('/certificados/pdf', array(CertificadosController::class, 'pdf'));
$app->get('/professor', array(ProfessorDashboardController::class, 'index'), array('auth'));
$app->get('/professor/dashboard', array(ProfessorDashboardController::class, 'index'), array('auth'));
$app->get('/professor/catalogo', array(ProfessorCatalogoController::class, 'index'), array('auth', 'permission:catalogo.professor.ver'));
$app->get('/professor/area-curso', array(ProfessorAreaCursoController::class, 'index'), array('auth', 'permission:area_curso.professor.ver'));
$app->post('/professor/area-curso/instrucoes', array(ProfessorAreaCursoController::class, 'salvarInstrucao'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/modulos', array(ProfessorAreaCursoController::class, 'salvarModulo'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/aulas', array(ProfessorAreaCursoController::class, 'salvarAula'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/materiais', array(ProfessorAreaCursoController::class, 'salvarMaterial'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/atividades', array(ProfessorAreaCursoController::class, 'salvarAtividade'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/atividades/status', array(ProfessorAreaCursoController::class, 'alterarStatusAtividade'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/atividades/entregas/corrigir', array(ProfessorAreaCursoController::class, 'corrigirEntrega'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/atividades/entregas/devolver', array(ProfessorAreaCursoController::class, 'devolverEntrega'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->get('/professor/area-curso/atividades/entregas/arquivo', array(ProfessorAreaCursoController::class, 'entregaArquivo'), array('auth', 'permission:area_curso.professor.ver'));
$app->post('/professor/area-curso/links', array(ProfessorAreaCursoController::class, 'salvarLink'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/excluir', array(ProfessorAreaCursoController::class, 'excluir'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/modulo/salvar', array(ProfessorAreaCursoController::class, 'salvarConteudoModulo'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/modulo/arquivar', array(ProfessorAreaCursoController::class, 'arquivarConteudoModulo'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/modulo/duplicar', array(ProfessorAreaCursoController::class, 'duplicarConteudoModulo'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/modulos/ordenar', array(ProfessorAreaCursoController::class, 'ordenarConteudoModulos'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/item/salvar', array(ProfessorAreaCursoController::class, 'salvarConteudoItem'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/item/arquivar', array(ProfessorAreaCursoController::class, 'arquivarConteudoItem'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/item/duplicar', array(ProfessorAreaCursoController::class, 'duplicarConteudoItem'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/item/mover', array(ProfessorAreaCursoController::class, 'moverConteudoItem'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/itens/ordenar', array(ProfessorAreaCursoController::class, 'ordenarConteudoItens'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->get('/professor/area-curso/conteudo/arquivo/download', array(ProfessorAreaCursoController::class, 'downloadConteudoArquivo'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/area-curso/conteudo/avaliacoes/pendentes', array(ProfessorAreaCursoController::class, 'avaliacoesTextuaisPendentes'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/area-curso/conteudo/avaliacao/corrigir', array(ProfessorAreaCursoController::class, 'avaliacaoTextualCorrigir'), array('auth', 'permission:area_curso.professor.ver'));
$app->post('/professor/area-curso/conteudo/avaliacao/corrigir', array(ProfessorAreaCursoController::class, 'corrigirAvaliacaoTextual'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/conteudo/avaliacao/liberar-reenvio', array(ProfessorAreaCursoController::class, 'liberarReenvioAvaliacaoTextual'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->get('/professor/area-curso/conteudo/avaliacao/imagem', array(ProfessorAreaCursoController::class, 'entregaAvaliacaoImagem'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/area-curso/conteudo/avaliacoes/exportar', array(ProfessorAreaCursoController::class, 'exportarAvaliacoesConteudoCsv'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/area-curso/participantes', array(ProfessorAreaCursoController::class, 'participantes'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/area-curso/material', array(ProfessorAreaCursoController::class, 'material'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/academico', array(ProfessorAcademicoController::class, 'index'), array('auth', 'permission:academico.ver'));
$app->post('/professor/academico/configuracao', array(ProfessorAcademicoController::class, 'salvarConfiguracao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/presenca', array(ProfessorAcademicoController::class, 'registrarPresenca'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/avaliacao', array(ProfessorAcademicoController::class, 'salvarAvaliacao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/pergunta', array(ProfessorAcademicoController::class, 'salvarPergunta'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/nota', array(ProfessorAcademicoController::class, 'registrarNota'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/recalcular', array(ProfessorAcademicoController::class, 'recalcularAptidao'), array('auth', 'permission:academico.gerenciar'));
$app->get('/professor/financeiro', array(ProfessorFinanceiroController::class, 'index'), array('auth', 'permission:financeiro.professor.ver'));
