<?php

use App\Controllers\HomeController;
use App\Controllers\PagesController;
use App\Controllers\AuthController;
use App\Controllers\Admin\RbacController;
use App\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Controllers\Admin\CatalogoController as AdminCatalogoController;
use App\Controllers\Admin\CategoriasController as AdminCategoriasController;
use App\Controllers\Admin\CuponsController;
use App\Controllers\Admin\EmailsController;
use App\Controllers\Admin\FinanceiroController as AdminFinanceiroController;
use App\Controllers\Admin\ConfiguracoesGlobaisController;
use App\Controllers\Admin\CertificadosController as AdminCertificadosController;
use App\Controllers\Admin\ComprovantesPixController;
use App\Controllers\Admin\ProfessoresFiscaisController as AdminProfessoresFiscaisController;
use App\Controllers\Admin\RateiosController as AdminRateiosController;
use App\Controllers\Admin\PedidosController;
use App\Controllers\Admin\InscricoesController;
use App\Controllers\Admin\AcademicoController as AdminAcademicoController;
use App\Controllers\Admin\CursosController as AdminCursosController;
use App\Controllers\Admin\TurmasController;
use App\Controllers\Professor\CatalogoController as ProfessorCatalogoController;
use App\Controllers\Professor\DashboardController as ProfessorDashboardController;
use App\Controllers\CursosController as PublicCursosController;
use App\Controllers\CheckoutController;
use App\Controllers\AreaCursoController;
use App\Controllers\MeusCursosController;
use App\Controllers\CertificadosController;
use App\Controllers\Admin\AreaCursoController as AdminAreaCursoController;
use App\Controllers\Professor\AreaCursoController as ProfessorAreaCursoController;
use App\Controllers\Professor\AcademicoController as ProfessorAcademicoController;
use App\Controllers\Professor\FinanceiroController as ProfessorFinanceiroController;

$app->get('/', array(HomeController::class, 'index'));
$app->get('/cursos', array(PublicCursosController::class, 'index'));
$app->get('/cursos/detalhe', array(PublicCursosController::class, 'show'));
$app->get('/como-funciona', array(PagesController::class, 'comoFunciona'));
$app->get('/sobre', array(PagesController::class, 'sobre'));
$app->get('/contato', array(PagesController::class, 'contato'));
$app->get('/inscricao', array(CheckoutController::class, 'inscricao'));
$app->post('/inscricao', array(CheckoutController::class, 'inscricao'));
$app->get('/checkout/inscricao', array(CheckoutController::class, 'inscricao'));
$app->post('/checkout/inscricao', array(CheckoutController::class, 'inscricao'));
$app->get('/checkout/participantes', array(CheckoutController::class, 'participantes'));
$app->post('/checkout/participantes', array(CheckoutController::class, 'participantes'));
$app->get('/checkout/resumo', array(CheckoutController::class, 'resumo'));
$app->get('/checkout/cupom', array(CheckoutController::class, 'cupom'));
$app->post('/checkout/cupom', array(CheckoutController::class, 'cupom'));
$app->get('/checkout/comprovante', array(CheckoutController::class, 'comprovante'));
$app->post('/checkout/comprovante', array(CheckoutController::class, 'comprovante'));
$app->get('/checkout/sucesso', array(CheckoutController::class, 'sucesso'));
$app->get('/meus-cursos', array(MeusCursosController::class, 'index'), array('auth'));
$app->get('/area-curso', array(AreaCursoController::class, 'index'), array('auth'));
$app->get('/area-curso/modulo', array(AreaCursoController::class, 'modulo'), array('auth'));
$app->post('/area-curso/modulo/concluir-aula', array(AreaCursoController::class, 'concluirAula'), array('auth'));
$app->post('/area-curso/modulo/concluir-modulo', array(AreaCursoController::class, 'concluirModulo'), array('auth'));
$app->get('/area-curso/material', array(AreaCursoController::class, 'material'), array('auth'));
$app->get('/cadastro', array(AuthController::class, 'showRegister'));
$app->post('/cadastro', array(AuthController::class, 'register'));
$app->get('/login', array(AuthController::class, 'showLogin'));
$app->post('/login', array(AuthController::class, 'login'));
$app->post('/logout', array(AuthController::class, 'logout'));
$app->get('/recuperar-senha', array(AuthController::class, 'showForgotPassword'));
$app->post('/recuperar-senha', array(AuthController::class, 'requestPasswordReset'));
$app->get('/recuperar-senha/redefinir', array(AuthController::class, 'showResetPassword'));
$app->post('/recuperar-senha/redefinir', array(AuthController::class, 'resetPassword'));
$app->get('/esqueci-minha-senha', array(AuthController::class, 'showForgotPassword'));
$app->post('/esqueci-minha-senha', array(AuthController::class, 'requestPasswordReset'));
$app->get('/esqueci-minha-senha/redefinir', array(AuthController::class, 'showResetPassword'));
$app->post('/esqueci-minha-senha/redefinir', array(AuthController::class, 'resetPassword'));
$app->get('/admin/rbac', array(RbacController::class, 'index'), array('auth', 'permission:rbac.dashboard.ver'));
$app->get('/admin', array(AdminDashboardController::class, 'index'), array('auth'));
$app->get('/admin/dashboard', array(AdminDashboardController::class, 'index'), array('auth'));
$app->get('/admin/catalogo', array(AdminCatalogoController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/categorias', array(AdminCategoriasController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/categorias/criar', array(AdminCategoriasController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/categorias/criar', array(AdminCategoriasController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/categorias/editar', array(AdminCategoriasController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/categorias/editar', array(AdminCategoriasController::class, 'update'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/categorias/show', array(AdminCategoriasController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/categorias/excluir', array(AdminCategoriasController::class, 'destroy'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/rbac/perfis/permissoes', array(RbacController::class, 'syncProfilePermissions'), array('auth', 'permission:rbac.perfis.gerenciar'));
$app->post('/admin/rbac/usuarios/perfis', array(RbacController::class, 'syncUserProfiles'), array('auth', 'permission:rbac.perfis.gerenciar'));
$app->get('/admin/cursos', array(AdminCursosController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/cursos/criar', array(AdminCursosController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/cursos/criar', array(AdminCursosController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/cursos/editar', array(AdminCursosController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/cursos/editar', array(AdminCursosController::class, 'update'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/cursos/show', array(AdminCursosController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/cursos/excluir', array(AdminCursosController::class, 'destroy'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/cursos/status', array(AdminCursosController::class, 'updateStatus'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas', array(TurmasController::class, 'index'), array('auth', 'permission:conteudo.ver'));
$app->get('/admin/turmas/criar', array(TurmasController::class, 'create'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/criar', array(TurmasController::class, 'store'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas/editar', array(TurmasController::class, 'edit'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/editar', array(TurmasController::class, 'update'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/turmas/show', array(TurmasController::class, 'show'), array('auth', 'permission:conteudo.ver'));
$app->post('/admin/turmas/excluir', array(TurmasController::class, 'destroy'), array('auth', 'permission:conteudo.gerenciar'));
$app->post('/admin/turmas/status', array(TurmasController::class, 'updateStatus'), array('auth', 'permission:conteudo.gerenciar'));
$app->get('/admin/professores-fiscais', array(AdminProfessoresFiscaisController::class, 'index'), array('auth', 'permission:financeiro.ver'));
$app->get('/admin/professores-fiscais/criar', array(AdminProfessoresFiscaisController::class, 'create'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/professores-fiscais/criar', array(AdminProfessoresFiscaisController::class, 'store'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/professores-fiscais/editar', array(AdminProfessoresFiscaisController::class, 'edit'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/professores-fiscais/editar', array(AdminProfessoresFiscaisController::class, 'update'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/professores-fiscais/show', array(AdminProfessoresFiscaisController::class, 'show'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/professores-fiscais/excluir', array(AdminProfessoresFiscaisController::class, 'destroy'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/rateios', array(AdminRateiosController::class, 'index'), array('auth', 'permission:financeiro.ver'));
$app->get('/admin/rateios/criar', array(AdminRateiosController::class, 'create'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/rateios/criar', array(AdminRateiosController::class, 'store'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/rateios/editar', array(AdminRateiosController::class, 'edit'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/rateios/editar', array(AdminRateiosController::class, 'update'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/rateios/show', array(AdminRateiosController::class, 'show'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/rateios/excluir', array(AdminRateiosController::class, 'destroy'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/pedidos', array(PedidosController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/pedidos/show', array(PedidosController::class, 'show'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/aprovar', array(PedidosController::class, 'aprovar'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/marcar-pendencia', array(PedidosController::class, 'marcarPendencia'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/solicitar-reenvio', array(PedidosController::class, 'solicitarReenvio'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/inscricoes', array(InscricoesController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/inscricoes/status', array(InscricoesController::class, 'alterarStatus'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/comprovantes-pix', array(ComprovantesPixController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/comprovantes-pix/aprovar', array(ComprovantesPixController::class, 'aprovar'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/comprovantes-pix/reprovar', array(ComprovantesPixController::class, 'reprovar'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/academico', array(AdminAcademicoController::class, 'index'), array('auth', 'permission:academico.ver'));
$app->post('/admin/academico/configuracao', array(AdminAcademicoController::class, 'salvarConfiguracao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/presenca', array(AdminAcademicoController::class, 'registrarPresenca'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/avaliacao', array(AdminAcademicoController::class, 'salvarAvaliacao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/pergunta', array(AdminAcademicoController::class, 'salvarPergunta'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/nota', array(AdminAcademicoController::class, 'registrarNota'), array('auth', 'permission:academico.gerenciar'));
$app->post('/admin/academico/recalcular', array(AdminAcademicoController::class, 'recalcularAptidao'), array('auth', 'permission:academico.gerenciar'));
$app->get('/admin/cupons', array(CuponsController::class, 'index'), array('auth', 'permission:cupons.ver'));
$app->get('/admin/cupons/criar', array(CuponsController::class, 'create'), array('auth', 'permission:cupons.gerenciar'));
$app->post('/admin/cupons/criar', array(CuponsController::class, 'store'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/cupons/editar', array(CuponsController::class, 'edit'), array('auth', 'permission:cupons.gerenciar'));
$app->post('/admin/cupons/editar', array(CuponsController::class, 'update'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/cupons/resumo', array(CuponsController::class, 'show'), array('auth', 'permission:cupons.usos.ver'));
$app->post('/admin/cupons/excluir', array(CuponsController::class, 'destroy'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/emails', array(EmailsController::class, 'index'), array('auth', 'permission:emails.ver'));
$app->post('/admin/emails', array(EmailsController::class, 'save'), array('auth', 'permission:emails.gerenciar'));
$app->get('/admin/financeiro', array(AdminFinanceiroController::class, 'index'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/financeiro/apurar', array(AdminFinanceiroController::class, 'apurar'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/financeiro/repasses', array(AdminFinanceiroController::class, 'repasses'), array('auth', 'permission:financeiro.ver'));
$app->post('/admin/financeiro/repasses/gerar', array(AdminFinanceiroController::class, 'gerarRepasses'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/financeiro/professor-fiscal', array(AdminFinanceiroController::class, 'salvarProfessorFiscal'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/financeiro/documento', array(AdminFinanceiroController::class, 'registrarDocumento'), array('auth', 'permission:financeiro.gerenciar'));
$app->post('/admin/financeiro/pagamento', array(AdminFinanceiroController::class, 'registrarPagamento'), array('auth', 'permission:financeiro.gerenciar'));
$app->get('/admin/configuracoes-globais', array(ConfiguracoesGlobaisController::class, 'index'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais', array(ConfiguracoesGlobaisController::class, 'salvarInstitucional'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/certificados', array(ConfiguracoesGlobaisController::class, 'certificados'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/certificados', array(ConfiguracoesGlobaisController::class, 'salvarCertificados'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/financeiro', array(ConfiguracoesGlobaisController::class, 'financeiro'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/financeiro', array(ConfiguracoesGlobaisController::class, 'salvarFinanceiro'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/frontend', array(ConfiguracoesGlobaisController::class, 'frontend'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/frontend', array(ConfiguracoesGlobaisController::class, 'salvarFrontend'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/configuracoes-globais/seguranca', array(ConfiguracoesGlobaisController::class, 'seguranca'), array('auth', 'permission:configuracoes_globais.ver'));
$app->post('/admin/configuracoes-globais/seguranca', array(ConfiguracoesGlobaisController::class, 'salvarSeguranca'), array('auth', 'permission:configuracoes_globais.gerenciar'));
$app->get('/admin/area-curso', array(AdminAreaCursoController::class, 'index'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/instrucoes', array(AdminAreaCursoController::class, 'salvarInstrucao'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/modulos', array(AdminAreaCursoController::class, 'salvarModulo'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/aulas', array(AdminAreaCursoController::class, 'salvarAula'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/materiais', array(AdminAreaCursoController::class, 'salvarMaterial'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/links', array(AdminAreaCursoController::class, 'salvarLink'), array('auth', 'permission:area_curso.gerenciar'));
$app->post('/admin/area-curso/excluir', array(AdminAreaCursoController::class, 'excluir'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/participantes', array(AdminAreaCursoController::class, 'participantes'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/area-curso/material', array(AdminAreaCursoController::class, 'material'), array('auth', 'permission:area_curso.gerenciar'));
$app->get('/admin/certificados', array(AdminCertificadosController::class, 'index'), array('auth', 'permission:certificados.ver'));
$app->get('/admin/certificados/show', array(AdminCertificadosController::class, 'show'), array('auth', 'permission:certificados.ver'));
$app->get('/admin/certificados/emitir', array(AdminCertificadosController::class, 'emitir'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/emitir', array(AdminCertificadosController::class, 'emitir'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/reemitir', array(AdminCertificadosController::class, 'reemitir'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/cancelar', array(AdminCertificadosController::class, 'cancelar'), array('auth', 'permission:certificados.gerenciar'));
$app->post('/admin/certificados/revogar', array(AdminCertificadosController::class, 'revogar'), array('auth', 'permission:certificados.gerenciar'));
$app->get('/admin/certificados/pdf', array(AdminCertificadosController::class, 'pdf'), array('auth', 'permission:certificados.ver'));
$app->get('/certificados/validar', array(CertificadosController::class, 'validar'));
$app->post('/certificados/validar', array(CertificadosController::class, 'validar'));
$app->get('/certificados/show', array(CertificadosController::class, 'show'));
$app->get('/certificados/pdf', array(CertificadosController::class, 'pdf'));
$app->get('/professor', array(ProfessorDashboardController::class, 'index'), array('auth'));
$app->get('/professor/dashboard', array(ProfessorDashboardController::class, 'index'), array('auth'));
$app->get('/professor/catalogo', array(ProfessorCatalogoController::class, 'index'), array('auth', 'permission:catalogo.professor.ver'));
$app->get('/professor/area-curso', array(ProfessorAreaCursoController::class, 'index'), array('auth', 'permission:area_curso.professor.ver'));
$app->post('/professor/area-curso/instrucoes', array(ProfessorAreaCursoController::class, 'salvarInstrucao'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/modulos', array(ProfessorAreaCursoController::class, 'salvarModulo'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/aulas', array(ProfessorAreaCursoController::class, 'salvarAula'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/materiais', array(ProfessorAreaCursoController::class, 'salvarMaterial'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/links', array(ProfessorAreaCursoController::class, 'salvarLink'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->post('/professor/area-curso/excluir', array(ProfessorAreaCursoController::class, 'excluir'), array('auth', 'permission:area_curso.professor.gerenciar'));
$app->get('/professor/area-curso/participantes', array(ProfessorAreaCursoController::class, 'participantes'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/area-curso/material', array(ProfessorAreaCursoController::class, 'material'), array('auth', 'permission:area_curso.professor.ver'));
$app->get('/professor/academico', array(ProfessorAcademicoController::class, 'index'), array('auth', 'permission:academico.ver'));
$app->post('/professor/academico/configuracao', array(ProfessorAcademicoController::class, 'salvarConfiguracao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/presenca', array(ProfessorAcademicoController::class, 'registrarPresenca'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/avaliacao', array(ProfessorAcademicoController::class, 'salvarAvaliacao'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/pergunta', array(ProfessorAcademicoController::class, 'salvarPergunta'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/nota', array(ProfessorAcademicoController::class, 'registrarNota'), array('auth', 'permission:academico.gerenciar'));
$app->post('/professor/academico/recalcular', array(ProfessorAcademicoController::class, 'recalcularAptidao'), array('auth', 'permission:academico.gerenciar'));
$app->get('/professor/financeiro', array(ProfessorFinanceiroController::class, 'index'), array('auth', 'permission:financeiro.professor.ver'));
