<?php

use App\Controllers\HomeController;
use App\Controllers\AuthController;
use App\Controllers\Admin\RbacController;
use App\Controllers\Admin\CatalogoController as AdminCatalogoController;
use App\Controllers\Admin\CuponsController;
use App\Controllers\Admin\ComprovantesPixController;
use App\Controllers\Admin\PedidosController;
use App\Controllers\Admin\InscricoesController;
use App\Controllers\Admin\CursosController as AdminCursosController;
use App\Controllers\Admin\TurmasController;
use App\Controllers\Professor\CatalogoController as ProfessorCatalogoController;
use App\Controllers\CursosController as PublicCursosController;
use App\Controllers\CheckoutController;
use App\Controllers\MeusCursosController;

$app->get('/', array(HomeController::class, 'index'));
$app->get('/cursos', array(PublicCursosController::class, 'index'));
$app->get('/cursos/detalhe', array(PublicCursosController::class, 'show'));
$app->get('/checkout/inscricao', array(CheckoutController::class, 'inscricao'));
$app->post('/checkout/inscricao', array(CheckoutController::class, 'inscricao'));
$app->get('/checkout/participantes', array(CheckoutController::class, 'participantes'));
$app->post('/checkout/participantes', array(CheckoutController::class, 'participantes'));
$app->get('/checkout/resumo', array(CheckoutController::class, 'resumo'));
$app->get('/checkout/cupom', array(CheckoutController::class, 'cupom'));
$app->post('/checkout/cupom', array(CheckoutController::class, 'cupom'));
$app->get('/checkout/comprovante', array(CheckoutController::class, 'comprovante'));
$app->post('/checkout/comprovante', array(CheckoutController::class, 'comprovante'));
$app->get('/checkout/sucesso', array(CheckoutController::class, 'sucesso'));
$app->get('/meus-cursos', array(MeusCursosController::class, 'index'), array('auth'));
$app->get('/cadastro', array(AuthController::class, 'showRegister'));
$app->post('/cadastro', array(AuthController::class, 'register'));
$app->get('/login', array(AuthController::class, 'showLogin'));
$app->post('/login', array(AuthController::class, 'login'));
$app->post('/logout', array(AuthController::class, 'logout'));
$app->get('/recuperar-senha', array(AuthController::class, 'showForgotPassword'));
$app->post('/recuperar-senha', array(AuthController::class, 'requestPasswordReset'));
$app->get('/recuperar-senha/redefinir', array(AuthController::class, 'showResetPassword'));
$app->post('/recuperar-senha/redefinir', array(AuthController::class, 'resetPassword'));
$app->get('/esqueci-minha-senha', array(AuthController::class, 'showForgotPassword'));
$app->post('/esqueci-minha-senha', array(AuthController::class, 'requestPasswordReset'));
$app->get('/esqueci-minha-senha/redefinir', array(AuthController::class, 'showResetPassword'));
$app->post('/esqueci-minha-senha/redefinir', array(AuthController::class, 'resetPassword'));
$app->get('/admin/rbac', array(RbacController::class, 'index'), array('auth', 'permission:rbac.dashboard.ver'));
$app->post('/admin/rbac/perfis/permissoes', array(RbacController::class, 'syncProfilePermissions'), array('auth', 'permission:rbac.perfis.gerenciar'));
$app->post('/admin/rbac/usuarios/perfis', array(RbacController::class, 'syncUserProfiles'), array('auth', 'permission:rbac.perfis.gerenciar'));
$app->get('/admin/catalogo', array(AdminCatalogoController::class, 'index'), array('auth', 'permission:catalogo.ver'));
$app->get('/admin/cursos', array(AdminCursosController::class, 'index'), array('auth', 'permission:catalogo.ver'));
$app->get('/admin/turmas', array(TurmasController::class, 'index'), array('auth', 'permission:catalogo.ver'));
$app->get('/admin/pedidos', array(PedidosController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/pedidos/show', array(PedidosController::class, 'show'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/aprovar', array(PedidosController::class, 'aprovar'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/marcar-pendencia', array(PedidosController::class, 'marcarPendencia'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/pedidos/solicitar-reenvio', array(PedidosController::class, 'solicitarReenvio'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/inscricoes', array(InscricoesController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/inscricoes/status', array(InscricoesController::class, 'alterarStatus'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/comprovantes-pix', array(ComprovantesPixController::class, 'index'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/comprovantes-pix/aprovar', array(ComprovantesPixController::class, 'aprovar'), array('auth', 'permission:pedidos.ver'));
$app->post('/admin/comprovantes-pix/reprovar', array(ComprovantesPixController::class, 'reprovar'), array('auth', 'permission:pedidos.ver'));
$app->get('/admin/cupons', array(CuponsController::class, 'index'), array('auth', 'permission:cupons.ver'));
$app->get('/admin/cupons/criar', array(CuponsController::class, 'create'), array('auth', 'permission:cupons.gerenciar'));
$app->post('/admin/cupons/criar', array(CuponsController::class, 'store'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/cupons/editar', array(CuponsController::class, 'edit'), array('auth', 'permission:cupons.gerenciar'));
$app->post('/admin/cupons/editar', array(CuponsController::class, 'update'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/admin/cupons/resumo', array(CuponsController::class, 'show'), array('auth', 'permission:cupons.usos.ver'));
$app->post('/admin/cupons/excluir', array(CuponsController::class, 'destroy'), array('auth', 'permission:cupons.gerenciar'));
$app->get('/professor/catalogo', array(ProfessorCatalogoController::class, 'index'), array('auth', 'permission:catalogo.professor.ver'));
